# workflow name
name: Generate release-artifacts

# on events
on:
  release:
    types:
      - created

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
        arch: [ 'amd64', 'arm64' ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Build
        run: env GOARCH=${{matrix.arch}} go build -o dist/iplan-${{runner.os}}-${{matrix.arch}}
      # step 3: upload build-artifacts
      - uses: actions/upload-artifact@v2
        with:
          path: dist/**
